name: rental_management
description: "Property & Rental Management System - Tenant Side"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  
  # Networking
  http: ^1.1.0
  http_parser: ^4.0.2
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Media
  image_picker: ^1.0.7
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Offline Support
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  
  # Utilities
  intl: ^0.19.0
  sqflite_common_ffi: ^2.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
